# Generated by Django 5.0.2 on 2024-02-14 22:06

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', api.models.CustomUserManager()),
            ],
        ),
    ]
