# Generated by Django 5.0.2 on 2024-02-16 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
